# Generated by Django 5.0.7 on 2026-01-14 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_hours_per_week', models.IntegerField(default=40, verbose_name='Макс. часов в неделю')),
                ('min_hours_per_week', models.IntegerField(default=20, verbose_name='Мин. часов в неделю')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Часовая ставка')),
                ('qualifications', models.TextField(blank=True, verbose_name='Квалификации')),
                ('preferred_shifts', models.TextField(blank=True, verbose_name='Предпочитаемые смены')),
                ('unavailable_days', models.TextField(blank=True, verbose_name='Невозможные дни')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='OptimizationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название правила')),
                ('rule_type', models.CharField(choices=[('legal', 'Законодательное'), ('business', 'Бизнес-правило'), ('preference', 'Предпочтение')], default='business', max_length=20)),
                ('description', models.TextField(verbose_name='Описание правила')),
                ('min_employees_per_shift', models.IntegerField(blank=True, null=True, verbose_name='Мин. сотрудников в смену')),
                ('max_employees_per_shift', models.IntegerField(blank=True, null=True, verbose_name='Макс. сотрудников в смену')),
                ('max_consecutive_shifts', models.IntegerField(blank=True, null=True, verbose_name='Макс. смен подряд')),
                ('min_rest_hours', models.IntegerField(blank=True, null=True, verbose_name='Мин. часов отдыха между сменами')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('priority', models.IntegerField(default=1, verbose_name='Приоритет')),
            ],
            options={
                'verbose_name': 'Правило оптимизации',
                'verbose_name_plural': 'Правила оптимизации',
                'ordering': ['priority', 'rule_type'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название смены')),
                ('shift_type', models.CharField(choices=[('morning', 'Утренняя'), ('day', 'Дневная'), ('evening', 'Вечерняя'), ('night', 'Ночная'), ('special', 'Особая')], default='day', max_length=20)),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('required_employees', models.IntegerField(default=1, verbose_name='Требуемое количество сотрудников')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название графика')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На согласовании'), ('approved', 'Утвержден'), ('published', 'Опубликован')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'График работы',
                'verbose_name_plural': 'Графики работы',
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('status', models.CharField(choices=[('scheduled', 'Запланировано'), ('confirmed', 'Подтверждено'), ('completed', 'Выполнено'), ('cancelled', 'Отменено')], default='scheduled', max_length=20)),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Факт. часы')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee', verbose_name='Сотрудник')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.schedule')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shift', verbose_name='Смена')),
            ],
            options={
                'verbose_name': 'Назначение на смену',
                'verbose_name_plural': 'Назначения на смены',
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ShiftSwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Причина обмена')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved_by_employee', 'Одобрено сотрудником'), ('approved_by_manager', 'Одобрено менеджером'), ('completed', 'Завершено'), ('rejected', 'Отклонено')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('from_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_sent', to='core.employee')),
                ('shift_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shiftassignment', verbose_name='Смена для обмена')),
                ('to_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_received', to='core.employee')),
            ],
            options={
                'verbose_name': 'Заявка на обмен сменой',
                'verbose_name_plural': 'Заявки на обмен сменами',
            },
        ),
        migrations.CreateModel(
            name='TimeOffRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('vacation', 'Отпуск'), ('sick', 'Больничный'), ('personal', 'Личные обстоятельства'), ('other', 'Другое')], default='personal', max_length=20)),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('reason', models.TextField(verbose_name='Причина')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Утверждено'), ('rejected', 'Отклонено')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Заявка на отгул',
                'verbose_name_plural': 'Заявки на отгул',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('employee', 'Сотрудник'), ('manager', 'Менеджер'), ('planner', 'Планировщик'), ('admin', 'Администратор системы')], default='employee', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Отдел')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('current_role', models.CharField(blank=True, choices=[('employee', 'Сотрудник'), ('manager', 'Менеджер'), ('planner', 'Планировщик'), ('admin', 'Администратор системы')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to='core.userprofile'),
        ),
    ]
