# Generated by Django 5.0.7 on 2026-01-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='current_role',
            field=models.CharField(blank=True, choices=[('employee', 'Сотрудник'), ('manager', 'Менеджер'), ('planner', 'Планировщик'), ('admin', 'Администратор системы')], max_length=20, verbose_name='Текущая роль'),
        ),
    ]
