# Generated by Django 6.0.1 on 2026-01-23 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Начало слота')),
                ('end_time', models.TimeField(verbose_name='Окончание слота')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Доступность',
                'verbose_name_plural': 'Доступность',
                'unique_together': {('employee', 'date', 'start_time')},
            },
        ),
    ]
