# Generated by Django 5.0.7 on 2026-01-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userprofile_current_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='current_role',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('employee', 'Сотрудник'), ('studio_admin', 'Администратор'), ('manager', 'Руководитель')], default='employee', max_length=20),
        ),
    ]
