# Generated by Django 6.0.1 on 2026-01-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
    ]
