# Generated by Django 5.0.7 on 2026-01-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_userprofile_current_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='invitation_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время приглашения/сброса пароля'),
        ),
    ]
