# Generated by Django 5.0.7 on 2026-01-27 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_availability_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='availability_deadline_weekday',
            field=models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], default=3, verbose_name='Дедлайн для указания доступности'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На согласовании'), ('approved', 'Утвержден')], default='draft', max_length=20),
        ),
    ]
