# Generated by Django 5.0.7 on 2026-01-27 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_schedule_availability_deadline_weekday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(null=True)),
                ('comment', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='core.schedule')),
            ],
            options={
                'unique_together': {('schedule', 'employee')},
            },
        ),
    ]
