# Generated by Django 5.0.7 on 2026-01-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_scheduleapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='availability_deadline_time',
            field=models.TimeField(default='18:00', verbose_name='Время дедлайна'),
        ),
    ]
