# Generated by Django 5.0.7 on 2026-01-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_schedule_availability_deadline_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability_deadline_weekday', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], default=3, verbose_name='День дедлайна')),
                ('availability_deadline_time', models.TimeField(default='18:00', verbose_name='Время дедлайна')),
            ],
            options={
                'verbose_name': 'Глобальные настройки',
                'verbose_name_plural': 'Глобальные настройки',
            },
        ),
    ]
