# Generated by Django 5.0.7 on 2026-01-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_globalsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalSettings',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='availability_deadline_time',
            field=models.TimeField(verbose_name='Время дедлайна'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='availability_deadline_weekday',
            field=models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='Дедлайн для указания доступности'),
        ),
    ]
