# Generated by Django 5.0.7 on 2026-01-28 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_globalsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalSettings',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='availability_deadline_time',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='availability_deadline_weekday',
        ),
    ]
