# Generated by Django 5.2.11 on 2026-02-05 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_userprofile_patronymic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftswaprequest',
            options={'verbose_name': 'Заявка на обмен сменами', 'verbose_name_plural': 'Заявки на обмен сменами'},
        ),
        migrations.RemoveField(
            model_name='shiftswaprequest',
            name='shift_assignment',
        ),
        migrations.CreateModel(
            name='SwapShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shiftassignment', verbose_name='Смена для обмена')),
                ('swap_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='core.shiftswaprequest')),
            ],
            options={
                'verbose_name': 'Смена в обмене',
                'verbose_name_plural': 'Смены в обмене',
            },
        ),
    ]
