# Generated by Django 6.0.1 on 2026-02-02 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_userprofile_patronymic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='position',
        ),
    ]
