# Generated by Django 5.0.7 on 2026-02-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_shiftswaprequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='workout_types',
            field=models.ManyToManyField(blank=True, to='core.workouttype', verbose_name='Направления, которые ведёт'),
        ),
    ]
