# Generated by Django 5.0.7 on 2026-03-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_employee_workout_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_substitute',
            field=models.BooleanField(default=False, verbose_name='В пуле подменных тренеров'),
        ),
        migrations.AddField(
            model_name='employee',
            name='substitute_priority',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='Приоритет подмены'),
        ),
    ]
