# Generated by Django 5.2.11 on 2026-04-26 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_userprofile_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'verbose_name': 'Р”РѕСЃС‚СѓРїРЅРѕСЃС‚СЊ', 'verbose_name_plural': 'Р”РѕСЃС‚СѓРїРЅРѕСЃС‚СЊ'},
        ),
        migrations.AlterModelOptions(
            name='chatconversation',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Р”РёР°Р»РѕРі', 'verbose_name_plural': 'Р”РёР°Р»РѕРіРё'},
        ),
        migrations.AlterModelOptions(
            name='chatconversationpin',
            options={'ordering': ['-created_at'], 'verbose_name': 'Р—Р°РєСЂРµРїР»РµРЅРЅС‹Р№ РґРёР°Р»РѕРі', 'verbose_name_plural': 'Р—Р°РєСЂРµРїР»РµРЅРЅС‹Рµ РґРёР°Р»РѕРіРё'},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'РЎРѕРѕР±С‰РµРЅРёРµ С‡Р°С‚Р°', 'verbose_name_plural': 'РЎРѕРѕР±С‰РµРЅРёСЏ С‡Р°С‚Р°'},
        ),
        migrations.AlterModelOptions(
            name='chatmessageread',
            options={'verbose_name': 'РЎС‚Р°С‚СѓСЃ РїСЂРѕС‡С‚РµРЅРёСЏ СЃРѕРѕР±С‰РµРЅРёСЏ', 'verbose_name_plural': 'РЎС‚Р°С‚СѓСЃС‹ РїСЂРѕС‡С‚РµРЅРёСЏ СЃРѕРѕР±С‰РµРЅРёР№'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'РЎРѕС‚СЂСѓРґРЅРёРє', 'verbose_name_plural': 'РЎРѕС‚СЂСѓРґРЅРёРєРё'},
        ),
        migrations.AlterModelOptions(
            name='optimizationrule',
            options={'ordering': ['priority', 'rule_type'], 'verbose_name': 'РџСЂР°РІРёР»Рѕ РѕРїС‚РёРјРёР·Р°С†РёРё', 'verbose_name_plural': 'РџСЂР°РІРёР»Р° РѕРїС‚РёРјРёР·Р°С†РёРё'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Р“СЂР°С„РёРє СЂР°Р±РѕС‚С‹', 'verbose_name_plural': 'Р“СЂР°С„РёРєРё СЂР°Р±РѕС‚С‹'},
        ),
        migrations.AlterModelOptions(
            name='shiftassignment',
            options={'verbose_name': 'РќР°Р·РЅР°С‡РµРЅРёРµ РЅР° Р·Р°РЅСЏС‚РёРµ', 'verbose_name_plural': 'РќР°Р·РЅР°С‡РµРЅРёСЏ РЅР° Р·Р°РЅСЏС‚РёСЏ'},
        ),
        migrations.AlterModelOptions(
            name='shiftswaprequest',
            options={'verbose_name': 'Р—Р°СЏРІРєР° РЅР° РѕР±РјРµРЅ СЃРјРµРЅР°РјРё', 'verbose_name_plural': 'Р—Р°СЏРІРєРё РЅР° РѕР±РјРµРЅ СЃРјРµРЅР°РјРё'},
        ),
        migrations.AlterModelOptions(
            name='swapshift',
            options={'verbose_name': 'РЎРјРµРЅР° РІ РѕР±РјРµРЅРµ', 'verbose_name_plural': 'РЎРјРµРЅС‹ РІ РѕР±РјРµРЅРµ'},
        ),
        migrations.AlterModelOptions(
            name='timeoffrequest',
            options={'verbose_name': 'Р—Р°СЏРІРєР° РЅР° РѕС‚РіСѓР»', 'verbose_name_plural': 'Р—Р°СЏРІРєРё РЅР° РѕС‚РіСѓР»'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'РџСЂРѕС„РёР»СЊ РїРѕР»СЊР·РѕРІР°С‚РµР»СЏ', 'verbose_name_plural': 'РџСЂРѕС„РёР»Рё РїРѕР»СЊР·РѕРІР°С‚РµР»РµР№'},
        ),
        migrations.AlterModelOptions(
            name='workouttype',
            options={'verbose_name': 'РўРёРї Р·Р°РЅСЏС‚РёСЏ', 'verbose_name_plural': 'РўРёРїС‹ Р·Р°РЅСЏС‚РёР№'},
        ),
        migrations.AlterField(
            model_name='availability',
            name='date',
            field=models.DateField(verbose_name='Р”Р°С‚Р°'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile', verbose_name='РЎРѕС‚СЂСѓРґРЅРёРє'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='end_time',
            field=models.TimeField(verbose_name='РћРєРѕРЅС‡Р°РЅРёРµ СЃР»РѕС‚Р°'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Р”РѕСЃС‚СѓРїРµРЅ'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='start_time',
            field=models.TimeField(verbose_name='РќР°С‡Р°Р»Рѕ СЃР»РѕС‚Р°'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='РџРѕСЃР»РµРґРЅРµРµ РѕР±РЅРѕРІР»РµРЅРёРµ'),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='РЎРѕР·РґР°РЅ'),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='is_group',
            field=models.BooleanField(default=False, verbose_name='Р“СЂСѓРїРїРѕРІРѕР№ С‡Р°С‚'),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='participant_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations_as_a', to=settings.AUTH_USER_MODEL, verbose_name='РЈС‡Р°СЃС‚РЅРёРє A'),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='participant_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations_as_b', to=settings.AUTH_USER_MODEL, verbose_name='РЈС‡Р°СЃС‚РЅРёРє B'),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='chat_conversations', to=settings.AUTH_USER_MODEL, verbose_name='РЈС‡Р°СЃС‚РЅРёРєРё'),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='РќР°Р·РІР°РЅРёРµ РіСЂСѓРїРїС‹'),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='РћР±РЅРѕРІР»РµРЅ'),
        ),
        migrations.AlterField(
            model_name='chatconversationpin',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='core.chatconversation', verbose_name='Р”РёР°Р»РѕРі'),
        ),
        migrations.AlterField(
            model_name='chatconversationpin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Р—Р°РєСЂРµРїР»РµРЅРѕ РІ'),
        ),
        migrations.AlterField(
            model_name='chatconversationpin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_pins', to=settings.AUTH_USER_MODEL, verbose_name='РџРѕР»СЊР·РѕРІР°С‚РµР»СЊ'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.chatconversation', verbose_name='Р”РёР°Р»РѕРі'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='РћС‚РїСЂР°РІР»РµРЅРѕ'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='РџСЂРѕС‡РёС‚Р°РЅРѕ'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages_sent', to=settings.AUTH_USER_MODEL, verbose_name='РћС‚РїСЂР°РІРёС‚РµР»СЊ'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='text',
            field=models.TextField(verbose_name='РўРµРєСЃС‚ СЃРѕРѕР±С‰РµРЅРёСЏ'),
        ),
        migrations.AlterField(
            model_name='chatmessageread',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='core.chatmessage', verbose_name='РЎРѕРѕР±С‰РµРЅРёРµ'),
        ),
        migrations.AlterField(
            model_name='chatmessageread',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='РџСЂРѕС‡РёС‚Р°РЅРѕ РІ'),
        ),
        migrations.AlterField(
            model_name='chatmessageread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_message_read_states', to=settings.AUTH_USER_MODEL, verbose_name='РџРѕР»СЊР·РѕРІР°С‚РµР»СЊ'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Р§Р°СЃРѕРІР°СЏ СЃС‚Р°РІРєР°'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_substitute',
            field=models.BooleanField(default=False, verbose_name='Р’ РїСѓР»Рµ РїРѕРґРјРµРЅРЅС‹С… С‚СЂРµРЅРµСЂРѕРІ'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='max_hours_per_week',
            field=models.IntegerField(default=40, verbose_name='РњР°РєСЃ. С‡Р°СЃРѕРІ РІ РЅРµРґРµР»СЋ'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='min_hours_per_week',
            field=models.IntegerField(default=20, verbose_name='РњРёРЅ. С‡Р°СЃРѕРІ РІ РЅРµРґРµР»СЋ'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='preferred_shifts',
            field=models.TextField(blank=True, verbose_name='РџСЂРµРґРїРѕС‡РёС‚Р°РµРјС‹Рµ СЃРјРµРЅС‹'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='qualifications',
            field=models.TextField(blank=True, verbose_name='РљРІР°Р»РёС„РёРєР°С†РёРё'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='substitute_priority',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='РџСЂРёРѕСЂРёС‚РµС‚ РїРѕРґРјРµРЅС‹'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='unavailable_days',
            field=models.TextField(blank=True, verbose_name='РќРµРІРѕР·РјРѕР¶РЅС‹Рµ РґРЅРё'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='workout_types',
            field=models.ManyToManyField(blank=True, to='core.workouttype', verbose_name='РќР°РїСЂР°РІР»РµРЅРёСЏ, РєРѕС‚РѕСЂС‹Рµ РІРµРґС‘С‚'),
        ),
        migrations.AlterField(
            model_name='optimizationrule',
            name='description',
            field=models.TextField(verbose_name='РћРїРёСЃР°РЅРёРµ РїСЂР°РІРёР»Р°'),
        ),
        migrations.AlterField(
            model_name='optimizationrule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='РђРєС‚РёРІРЅРѕ'),
        ),
        migrations.AlterField(
            model_name='optimizationrule',
            name='max_consecutive_shifts',
            field=models.IntegerField(blank=True, null=True, verbose_name='РњР°РєСЃ. СЃРјРµРЅ РїРѕРґСЂСЏРґ'),
        ),
        migrations.AlterField(
            model_name='optimizationrule',
            name='max_employees_per_shift',
            field=models.IntegerField(blank=True, null=True, verbose_name='РњР°РєСЃ. СЃРѕС‚СЂСѓРґРЅРёРєРѕРІ РІ СЃРјРµРЅСѓ'),
        ),
        migrations.AlterField(
            model_name='optimizationrule',
            name='min_employees_per_shift',
            field=models.IntegerField(blank=True, null=True, verbose_name='РњРёРЅ. СЃРѕС‚СЂСѓРґРЅРёРєРѕРІ РІ СЃРјРµРЅСѓ'),
        ),
        migrations.AlterField(
            model_name='optimizationrule',
            name='min_rest_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='РњРёРЅ. С‡Р°СЃРѕРІ РѕС‚РґС‹С…Р° РјРµР¶РґСѓ СЃРјРµРЅР°РјРё'),
        ),
        migrations.AlterField(
            model_name='optimizationrule',
            name='name',
            field=models.CharField(max_length=200, verbose_name='РќР°Р·РІР°РЅРёРµ РїСЂР°РІРёР»Р°'),
        ),
        migrations.AlterField(
            model_name='optimizationrule',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='РџСЂРёРѕСЂРёС‚РµС‚'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Р”Р°С‚Р° СЃРѕР·РґР°РЅРёСЏ'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='РЎРѕР·РґР°С‚РµР»СЊ'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_date',
            field=models.DateField(verbose_name='Р”Р°С‚Р° РѕРєРѕРЅС‡Р°РЅРёСЏ'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.CharField(max_length=200, verbose_name='РќР°Р·РІР°РЅРёРµ РіСЂР°С„РёРєР°'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_date',
            field=models.DateField(verbose_name='Р”Р°С‚Р° РЅР°С‡Р°Р»Р°'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Р”Р°С‚Р° РѕР±РЅРѕРІР»РµРЅРёСЏ'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='actual_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Р¤Р°РєС‚. С‡Р°СЃС‹'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='date',
            field=models.DateField(verbose_name='Р”Р°С‚Р°'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile', verbose_name='РЎРѕС‚СЂСѓРґРЅРёРє'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Р’СЂРµРјСЏ РѕРєРѕРЅС‡Р°РЅРёСЏ'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='start_time',
            field=models.TimeField(verbose_name='Р’СЂРµРјСЏ РЅР°С‡Р°Р»Р°'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='workout_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.workouttype', verbose_name='РўРёРї Р·Р°РЅСЏС‚РёСЏ'),
        ),
        migrations.AlterField(
            model_name='shiftswaprequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Р”Р°С‚Р° СЃРѕР·РґР°РЅРёСЏ'),
        ),
        migrations.AlterField(
            model_name='shiftswaprequest',
            name='reason',
            field=models.TextField(verbose_name='РџСЂРёС‡РёРЅР° РѕР±РјРµРЅР°'),
        ),
        migrations.AlterField(
            model_name='shiftswaprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('approved_by_employee', 'Одобрено сотрудником'), ('approved_by_manager', 'Одобрено руководителем'), ('completed', 'Завершено'), ('rejected', 'Отклонено')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='swapshift',
            name='shift_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shiftassignment', verbose_name='РЎРјРµРЅР° РґР»СЏ РѕР±РјРµРЅР°'),
        ),
        migrations.AlterField(
            model_name='timeoffrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Р”Р°С‚Р° СЃРѕР·РґР°РЅРёСЏ'),
        ),
        migrations.AlterField(
            model_name='timeoffrequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee', verbose_name='РЎРѕС‚СЂСѓРґРЅРёРє'),
        ),
        migrations.AlterField(
            model_name='timeoffrequest',
            name='end_date',
            field=models.DateField(verbose_name='Р”Р°С‚Р° РѕРєРѕРЅС‡Р°РЅРёСЏ'),
        ),
        migrations.AlterField(
            model_name='timeoffrequest',
            name='reason',
            field=models.TextField(verbose_name='РџСЂРёС‡РёРЅР°'),
        ),
        migrations.AlterField(
            model_name='timeoffrequest',
            name='start_date',
            field=models.DateField(verbose_name='Р”Р°С‚Р° РЅР°С‡Р°Р»Р°'),
        ),
        migrations.AlterField(
            model_name='timeoffrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Р”Р°С‚Р° РѕР±РЅРѕРІР»РµРЅРёСЏ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='invitation_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Р’СЂРµРјСЏ РїСЂРёРіР»Р°С€РµРЅРёСЏ/СЃР±СЂРѕСЃР° РїР°СЂРѕР»СЏ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='patronymic',
            field=models.CharField(blank=True, max_length=150, verbose_name='РћС‚С‡РµСЃС‚РІРѕ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='РўРµР»РµС„РѕРЅ'),
        ),
        migrations.AlterField(
            model_name='workouttype',
            name='description',
            field=models.TextField(blank=True, verbose_name='РћРїРёСЃР°РЅРёРµ'),
        ),
        migrations.AlterField(
            model_name='workouttype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='РќР°Р·РІР°РЅРёРµ Р·Р°РЅСЏС‚РёСЏ'),
        ),
    ]
