# Generated by Django 5.2.11 on 2026-04-28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_chat_attachments_and_group_management'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HourRateChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Часовая ставка')),
                ('effective_from', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Действует с')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hour_rate_changes', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'Изменение часовой ставки',
                'verbose_name_plural': 'История изменения часовой ставки',
                'ordering': ['-effective_from', '-id'],
            },
        ),
    ]
