# Generated by Django 5.2.11 on 2026-04-28

from datetime import datetime

from django.db import migrations
from django.utils import timezone


def seed_default_hour_rate(apps, schema_editor):
    HourRateChange = apps.get_model('core', 'HourRateChange')
    if HourRateChange.objects.exists():
        return

    dt = datetime(2000, 1, 1, 0, 0, 0)
    if timezone.is_naive(dt):
        dt = timezone.make_aware(dt, timezone.get_current_timezone())

    HourRateChange.objects.create(
        rate=400,
        effective_from=dt,
        changed_by=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_hourratechange'),
    ]

    operations = [
        migrations.RunPython(seed_default_hour_rate, migrations.RunPython.noop),
    ]
