# Generated by Django 5.2.11 on 2026-05-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_workouttype_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionrule',
            name='rule_type',
            field=models.CharField(choices=[('weekly_limit', 'Лимит в неделю'), ('calm_consecutive', 'Ограничение спокойных подряд'), ('alternation', 'Чередование категорий'), ('daily_duplicate_limit', 'Запрет дублей в день')], max_length=32, verbose_name='Тип правила'),
        ),
    ]
