# Generated by Django 5.2.11 on 2026-06-14 19:03


import django.db.models.deletion

import django.utils.timezone

from django.conf import settings

from django.db import migrations, models




class Migration(migrations.Migration):


    dependencies = [

        ('core', '0029_workouttype_descriptions'),

        migrations.swappable_dependency(settings.AUTH_USER_MODEL),

    ]


    operations = [

        migrations.AlterModelOptions(

            name='availability',

            options={'verbose_name': 'Доступность', 'verbose_name_plural': 'Доступность'},

        ),

        migrations.AlterModelOptions(

            name='chatconversation',

            options={'ordering': ['-updated_at'], 'verbose_name': 'Диалог', 'verbose_name_plural': 'Диалоги'},

        ),

        migrations.AlterModelOptions(

            name='chatconversationpin',

            options={'ordering': ['-created_at'], 'verbose_name': 'Закрепленный диалог', 'verbose_name_plural': 'Закрепленные диалоги'},

        ),

        migrations.AlterModelOptions(

            name='chatmessage',

            options={'ordering': ['created_at'], 'verbose_name': 'Сообщение чата', 'verbose_name_plural': 'Сообщения чата'},

        ),

        migrations.AlterModelOptions(

            name='chatmessageattachment',

            options={'ordering': ['id'], 'verbose_name': 'Вложение сообщения', 'verbose_name_plural': 'Вложения сообщений'},

        ),

        migrations.AlterModelOptions(

            name='chatmessageread',

            options={'verbose_name': 'Статус прочтения сообщения', 'verbose_name_plural': 'Статусы прочтения сообщений'},

        ),

        migrations.AlterModelOptions(

            name='distributionrule',

            options={'ordering': ['priority', 'id'], 'verbose_name': 'Правило распределения', 'verbose_name_plural': 'Правила распределения'},

        ),

        migrations.AlterModelOptions(

            name='employee',

            options={},

        ),

        migrations.AlterModelOptions(

            name='hourratechange',

            options={'ordering': ['-effective_from', '-id'], 'verbose_name': '�\x98зменение часовой ставки', 'verbose_name_plural': '�\x98стория изменения часовой ставки'},

        ),

        migrations.AlterModelOptions(

            name='optimizationrule',

            options={'ordering': ['priority', 'rule_type'], 'verbose_name': 'Правило оптимизации', 'verbose_name_plural': 'Правила оптимизации'},

        ),

        migrations.AlterModelOptions(

            name='schedule',

            options={'verbose_name': 'График работы', 'verbose_name_plural': 'Графики работы'},

        ),

        migrations.AlterModelOptions(

            name='scheduleversion',

            options={'ordering': ['-version_number', '-id'], 'verbose_name': 'Версия графика', 'verbose_name_plural': 'Версии графиков'},

        ),

        migrations.AlterModelOptions(

            name='scheduleversionassignment',

            options={'ordering': ['date', 'start_time', 'id'], 'verbose_name': 'Снимок смены версии', 'verbose_name_plural': 'Снимки смен версий'},

        ),

        migrations.AlterModelOptions(

            name='shiftassignment',

            options={'verbose_name': 'Назначение на занятие', 'verbose_name_plural': 'Назначения на занятия'},

        ),

        migrations.AlterModelOptions(

            name='shiftswaprequest',

            options={'verbose_name': 'Заявка на обмен сменами', 'verbose_name_plural': 'Заявки на обмен сменами'},

        ),

        migrations.AlterModelOptions(

            name='swapshift',

            options={'verbose_name': 'Смена в обмене', 'verbose_name_plural': 'Смены в обмене'},

        ),

        migrations.AlterModelOptions(

            name='userprofile',

            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},

        ),

        migrations.AlterModelOptions(

            name='workouttype',

            options={'verbose_name': 'Тип занятия', 'verbose_name_plural': 'Типы занятий'},

        ),

        migrations.AlterField(

            model_name='availability',

            name='date',

            field=models.DateField(verbose_name='Дата'),

        ),

        migrations.AlterField(

            model_name='availability',

            name='employee',

            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile', verbose_name='Сотрудник'),

        ),

        migrations.AlterField(

            model_name='availability',

            name='end_time',

            field=models.TimeField(verbose_name='Окончание слота'),

        ),

        migrations.AlterField(

            model_name='availability',

            name='is_available',

            field=models.BooleanField(default=True, verbose_name='Доступен'),

        ),

        migrations.AlterField(

            model_name='availability',

            name='start_time',

            field=models.TimeField(verbose_name='Начало слота'),

        ),

        migrations.AlterField(

            model_name='availability',

            name='updated_at',

            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),

        ),

        migrations.AlterField(

            model_name='chatconversation',

            name='created_at',

            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),

        ),

        migrations.AlterField(

            model_name='chatconversation',

            name='created_by',

            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_groups_created', to=settings.AUTH_USER_MODEL, verbose_name='Создатель группы'),

        ),

        migrations.AlterField(

            model_name='chatconversation',

            name='is_group',

            field=models.BooleanField(default=False, verbose_name='Групповой чат'),

        ),

        migrations.AlterField(

            model_name='chatconversation',

            name='participant_a',

            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations_as_a', to=settings.AUTH_USER_MODEL, verbose_name='Участник A'),

        ),

        migrations.AlterField(

            model_name='chatconversation',

            name='participant_b',

            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations_as_b', to=settings.AUTH_USER_MODEL, verbose_name='Участник B'),

        ),

        migrations.AlterField(

            model_name='chatconversation',

            name='participants',

            field=models.ManyToManyField(blank=True, related_name='chat_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),

        ),

        migrations.AlterField(

            model_name='chatconversation',

            name='title',

            field=models.CharField(blank=True, max_length=200, verbose_name='Название группы'),

        ),

        migrations.AlterField(

            model_name='chatconversation',

            name='updated_at',

            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),

        ),

        migrations.AlterField(

            model_name='chatconversationpin',

            name='conversation',

            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='core.chatconversation', verbose_name='Диалог'),

        ),

        migrations.AlterField(

            model_name='chatconversationpin',

            name='created_at',

            field=models.DateTimeField(auto_now_add=True, verbose_name='Закреплено в'),

        ),

        migrations.AlterField(

            model_name='chatconversationpin',

            name='user',

            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_pins', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),

        ),

        migrations.AlterField(

            model_name='chatmessage',

            name='conversation',

            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.chatconversation', verbose_name='Диалог'),

        ),

        migrations.AlterField(

            model_name='chatmessage',

            name='created_at',

            field=models.DateTimeField(auto_now_add=True, verbose_name='Отправлено'),

        ),

        migrations.AlterField(

            model_name='chatmessage',

            name='is_read',

            field=models.BooleanField(default=False, verbose_name='Прочитано'),

        ),

        migrations.AlterField(

            model_name='chatmessage',

            name='sender',

            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages_sent', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),

        ),

        migrations.AlterField(

            model_name='chatmessage',

            name='text',

            field=models.TextField(blank=True, default='', verbose_name='Текст сообщения'),

        ),

        migrations.AlterField(

            model_name='chatmessageattachment',

            name='file',

            field=models.FileField(upload_to='chat_files/%Y/%m/%d/', verbose_name='Файл'),

        ),

        migrations.AlterField(

            model_name='chatmessageattachment',

            name='message',

            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.chatmessage', verbose_name='Сообщение'),

        ),

        migrations.AlterField(

            model_name='chatmessageattachment',

            name='original_name',

            field=models.CharField(max_length=255, verbose_name='�\x98мя файла'),

        ),

        migrations.AlterField(

            model_name='chatmessageattachment',

            name='size',

            field=models.PositiveIntegerField(default=0, verbose_name='�\xa0азмер (байт)'),

        ),

        migrations.AlterField(

            model_name='chatmessageattachment',

            name='uploaded_at',

            field=models.DateTimeField(auto_now_add=True, verbose_name='Загружен'),

        ),

        migrations.AlterField(

            model_name='chatmessageread',

            name='message',

            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='core.chatmessage', verbose_name='Сообщение'),

        ),

        migrations.AlterField(

            model_name='chatmessageread',

            name='read_at',

            field=models.DateTimeField(blank=True, null=True, verbose_name='Прочитано в'),

        ),

        migrations.AlterField(

            model_name='chatmessageread',

            name='user',

            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_message_read_states', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),

        ),

        migrations.AlterField(

            model_name='distributionrule',

            name='created_at',

            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),

        ),

        migrations.AlterField(

            model_name='distributionrule',

            name='created_by',

            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_rules_created', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),

        ),

        migrations.AlterField(

            model_name='distributionrule',

            name='is_active',

            field=models.BooleanField(default=True, verbose_name='Активно'),

        ),

        migrations.AlterField(

            model_name='distributionrule',

            name='name',

            field=models.CharField(max_length=200, verbose_name='Название правила'),

        ),

        migrations.AlterField(

            model_name='distributionrule',

            name='params_json',

            field=models.JSONField(blank=True, default=dict, verbose_name='Параметры (JSON)'),

        ),

        migrations.AlterField(

            model_name='distributionrule',

            name='priority',

            field=models.PositiveIntegerField(default=100, verbose_name='Приоритет'),

        ),

        migrations.AlterField(

            model_name='distributionrule',

            name='rule_type',

            field=models.CharField(choices=[('weekly_limit', 'Лимит в неделю'), ('calm_consecutive', 'Ограничение спокойных подряд'), ('alternation', 'Чередование категорий'), ('daily_duplicate_limit', 'Запрет дублей в день')], max_length=32, verbose_name='Тип правила'),

        ),

        migrations.AlterField(

            model_name='distributionrule',

            name='severity',

            field=models.CharField(choices=[('hard', 'Жесткое'), ('soft', 'Мягкое')], default='hard', max_length=10, verbose_name='Жесткость'),

        ),

        migrations.AlterField(

            model_name='distributionrule',

            name='source_text',

            field=models.TextField(verbose_name='Текст правила'),

        ),

        migrations.AlterField(

            model_name='distributionrule',

            name='updated_at',

            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),

        ),

        migrations.AlterField(

            model_name='employee',

            name='hourly_rate',

            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Часовая ставка'),

        ),

        migrations.AlterField(

            model_name='employee',

            name='is_substitute',

            field=models.BooleanField(default=False, verbose_name='В пуле подменных тренеров'),

        ),

        migrations.AlterField(

            model_name='employee',

            name='max_hours_per_week',

            field=models.IntegerField(default=40, verbose_name='Макс. часов в неделю'),

        ),

        migrations.AlterField(

            model_name='employee',

            name='min_hours_per_week',

            field=models.IntegerField(default=20, verbose_name='Мин. часов в неделю'),

        ),

        migrations.AlterField(

            model_name='employee',

            name='preferred_shifts',

            field=models.TextField(blank=True, verbose_name='Предпочитаемые смены'),

        ),

        migrations.AlterField(

            model_name='employee',

            name='qualifications',

            field=models.TextField(blank=True, verbose_name='Квалификации'),

        ),

        migrations.AlterField(

            model_name='employee',

            name='substitute_priority',

            field=models.PositiveSmallIntegerField(default=50, verbose_name='Приоритет подмены'),

        ),

        migrations.AlterField(

            model_name='employee',

            name='unavailable_days',

            field=models.TextField(blank=True, verbose_name='Невозможные дни'),

        ),

        migrations.AlterField(

            model_name='employee',

            name='workout_types',

            field=models.ManyToManyField(blank=True, to='core.workouttype', verbose_name='Направления, которые ведёт'),

        ),

        migrations.AlterField(

            model_name='hourratechange',

            name='changed_by',

            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hour_rate_changes', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил'),

        ),

        migrations.AlterField(

            model_name='hourratechange',

            name='created_at',

            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),

        ),

        migrations.AlterField(

            model_name='hourratechange',

            name='effective_from',

            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Действует с'),

        ),

        migrations.AlterField(

            model_name='hourratechange',

            name='rate',

            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Часовая ставка'),

        ),

        migrations.AlterField(

            model_name='optimizationrule',

            name='description',

            field=models.TextField(verbose_name='Описание правила'),

        ),

        migrations.AlterField(

            model_name='optimizationrule',

            name='is_active',

            field=models.BooleanField(default=True, verbose_name='Активно'),

        ),

        migrations.AlterField(

            model_name='optimizationrule',

            name='max_consecutive_shifts',

            field=models.IntegerField(blank=True, null=True, verbose_name='Макс. смен подряд'),

        ),

        migrations.AlterField(

            model_name='optimizationrule',

            name='max_employees_per_shift',

            field=models.IntegerField(blank=True, null=True, verbose_name='Макс. сотрудников в смену'),

        ),

        migrations.AlterField(

            model_name='optimizationrule',

            name='min_employees_per_shift',

            field=models.IntegerField(blank=True, null=True, verbose_name='Мин. сотрудников в смену'),

        ),

        migrations.AlterField(

            model_name='optimizationrule',

            name='min_rest_hours',

            field=models.IntegerField(blank=True, null=True, verbose_name='Мин. часов отдыха между сменами'),

        ),

        migrations.AlterField(

            model_name='optimizationrule',

            name='name',

            field=models.CharField(max_length=200, verbose_name='Название правила'),

        ),

        migrations.AlterField(

            model_name='optimizationrule',

            name='priority',

            field=models.IntegerField(default=1, verbose_name='Приоритет'),

        ),

        migrations.AlterField(

            model_name='optimizationrule',

            name='rule_type',

            field=models.CharField(choices=[('legal', 'Законодательное'), ('business', 'Бизнес-правило'), ('preference', 'Предпочтение')], default='business', max_length=20),

        ),

        migrations.AlterField(

            model_name='schedule',

            name='created_at',

            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),

        ),

        migrations.AlterField(

            model_name='schedule',

            name='created_by',

            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),

        ),

        migrations.AlterField(

            model_name='schedule',

            name='end_date',

            field=models.DateField(verbose_name='Дата окончания'),

        ),

        migrations.AlterField(

            model_name='schedule',

            name='name',

            field=models.CharField(max_length=200, verbose_name='Название графика'),

        ),

        migrations.AlterField(

            model_name='schedule',

            name='start_date',

            field=models.DateField(verbose_name='Дата начала'),

        ),

        migrations.AlterField(

            model_name='schedule',

            name='status',

            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На согласовании'), ('approved', 'Утвержден')], default='draft', max_length=20),

        ),

        migrations.AlterField(

            model_name='schedule',

            name='updated_at',

            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),

        ),

        migrations.AlterField(

            model_name='scheduleversion',

            name='change_note',

            field=models.CharField(blank=True, max_length=255, verbose_name='Комментарий к версии'),

        ),

        migrations.AlterField(

            model_name='scheduleversion',

            name='change_source',

            field=models.CharField(blank=True, help_text='create, update, restore', max_length=30, verbose_name='�\x98сточник изменения'),

        ),

        migrations.AlterField(

            model_name='scheduleversion',

            name='created_at',

            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания версии'),

        ),

        migrations.AlterField(

            model_name='scheduleversion',

            name='created_by',

            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedule_versions', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал версию'),

        ),

        migrations.AlterField(

            model_name='scheduleversion',

            name='schedule',

            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.schedule', verbose_name='График'),

        ),

        migrations.AlterField(

            model_name='scheduleversion',

            name='schedule_name',

            field=models.CharField(max_length=200, verbose_name='Название графика в версии'),

        ),

        migrations.AlterField(

            model_name='scheduleversion',

            name='version_number',

            field=models.PositiveIntegerField(verbose_name='Номер версии'),

        ),

        migrations.AlterField(

            model_name='scheduleversionassignment',

            name='date',

            field=models.DateField(verbose_name='Дата'),

        ),

        migrations.AlterField(

            model_name='scheduleversionassignment',

            name='employee',

            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.userprofile', verbose_name='Сотрудник'),

        ),

        migrations.AlterField(

            model_name='scheduleversionassignment',

            name='end_time',

            field=models.TimeField(verbose_name='Время окончания'),

        ),

        migrations.AlterField(

            model_name='scheduleversionassignment',

            name='schedule_version',

            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.scheduleversion', verbose_name='Версия графика'),

        ),

        migrations.AlterField(

            model_name='scheduleversionassignment',

            name='start_time',

            field=models.TimeField(verbose_name='Время начала'),

        ),

        migrations.AlterField(

            model_name='scheduleversionassignment',

            name='workout_type',

            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.workouttype', verbose_name='Тип занятия'),

        ),

        migrations.AlterField(

            model_name='shiftassignment',

            name='actual_hours',

            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Факт. часы'),

        ),

        migrations.AlterField(

            model_name='shiftassignment',

            name='date',

            field=models.DateField(verbose_name='Дата'),

        ),

        migrations.AlterField(

            model_name='shiftassignment',

            name='employee',

            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile', verbose_name='Сотрудник'),

        ),

        migrations.AlterField(

            model_name='shiftassignment',

            name='end_time',

            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания'),

        ),

        migrations.AlterField(

            model_name='shiftassignment',

            name='start_time',

            field=models.TimeField(verbose_name='Время начала'),

        ),

        migrations.AlterField(

            model_name='shiftassignment',

            name='status',

            field=models.CharField(choices=[('scheduled', 'Запланировано'), ('confirmed', 'Подтверждено'), ('completed', 'Выполнено'), ('cancelled', 'Отменено')], default='scheduled', max_length=20),

        ),

        migrations.AlterField(

            model_name='shiftassignment',

            name='workout_type',

            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.workouttype', verbose_name='Тип занятия'),

        ),

        migrations.AlterField(

            model_name='shiftswaprequest',

            name='created_at',

            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),

        ),

        migrations.AlterField(

            model_name='shiftswaprequest',

            name='reason',

            field=models.TextField(verbose_name='Причина обмена'),

        ),

        migrations.AlterField(

            model_name='shiftswaprequest',

            name='status',

            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('approved_by_employee', 'Одобрено сотрудником'), ('approved_by_manager', 'Одобрено руководителем'), ('completed', 'Завершено'), ('rejected', 'Отклонено')], default='pending', max_length=30),

        ),

        migrations.AlterField(

            model_name='swapshift',

            name='shift_assignment',

            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shiftassignment', verbose_name='Смена для обмена'),

        ),

        migrations.AlterField(

            model_name='userprofile',

            name='avatar',

            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),

        ),

        migrations.AlterField(

            model_name='userprofile',

            name='invitation_timestamp',

            field=models.DateTimeField(blank=True, null=True, verbose_name='Время приглашения/сброса пароля'),

        ),

        migrations.AlterField(

            model_name='userprofile',

            name='patronymic',

            field=models.CharField(blank=True, max_length=150, verbose_name='Отчество'),

        ),

        migrations.AlterField(

            model_name='userprofile',

            name='phone',

            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),

        ),

        migrations.AlterField(

            model_name='userprofile',

            name='role',

            field=models.CharField(choices=[('employee', 'Сотрудник'), ('manager', '�\xa0уководитель')], default='employee', max_length=20),

        ),

        migrations.AlterField(

            model_name='workouttype',

            name='category',

            field=models.CharField(choices=[('calm', 'Спокойные'), ('cardio', 'Кардио'), ('strength', 'Силовые'), ('dance', 'Танцы'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория занятия'),

        ),

        migrations.AlterField(

            model_name='workouttype',

            name='description',

            field=models.TextField(blank=True, verbose_name='Описание'),

        ),

        migrations.AlterField(

            model_name='workouttype',

            name='name',

            field=models.CharField(max_length=100, verbose_name='Название занятия'),

        ),

        migrations.DeleteModel(

            name='TimeOffRequest',

        ),

    ]

