# Generated by Django 5.2.13 on 2026-06-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_availability_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hourratechange',
            options={'ordering': ['-effective_from', '-id'], 'verbose_name': '�?зменение часовой ставки', 'verbose_name_plural': '�?стория изменения часовой ставки'},
        ),
        migrations.AddField(
            model_name='scheduleapproval',
            name='manager_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessageattachment',
            name='original_name',
            field=models.CharField(max_length=255, verbose_name='�?мя файла'),
        ),
        migrations.AlterField(
            model_name='chatmessageattachment',
            name='size',
            field=models.PositiveIntegerField(default=0, verbose_name='Размер (байт)'),
        ),
        migrations.AlterField(
            model_name='scheduleversion',
            name='change_source',
            field=models.CharField(blank=True, help_text='create, update, restore', max_length=30, verbose_name='�?сточник изменения'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('employee', 'Сотрудник'), ('manager', 'Руководитель')], default='employee', max_length=20),
        ),
    ]
